name: ✨ 功能请求
description: 为本项目提出一个新想法
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提出改进建议！

  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能解决了什么问题？
      placeholder: 每次我想要 ... 的时候，都不得不 ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 你希望看到什么样的方案？
      placeholder: 我希望能有一个 ... 按钮/选项
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你考虑过哪些替代方案？
